import {objectSearched} from './objectSearched'

export const lastSearched: objectSearched[] = [
	{	id: 1,
		companyType: 'Kancelaria prawnicza',
		transactionType: 'Wynajem',
		objectType: 'biuro',
		objectLocation: 'Warszawa',
		objectAreaMin: 250,
		objectAreaMax: 350,
		objectPriceMin: 10000,
		objectPriceMax: 15000},
	{	id: 2,
		companyType: 'Salon kosmetyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 50,
		objectAreaMax: 80,
		objectPriceMin: 1500,
		objectPriceMax: 3000},
	{	id: 3,
		companyType: 'Programista',
		transactionType: 'Wynajem',
		objectType: 'biuro',
		objectLocation: 'Warszawa',
		objectAreaMin: 15,
		objectAreaMax: 20,
		objectPriceMin: 500,
		objectPriceMax: 800},
	{	id: 4,
		companyType: 'Sklep specjalistyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 150,
		objectAreaMax: 200,
		objectPriceMin: 5000,
		objectPriceMax: 8000},
	{	id: 5,
		companyType: 'Salon kosmetyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 50,
		objectAreaMax: 80,
		objectPriceMin: 1500,
		objectPriceMax: 3000},
	{	id: 6,
		companyType: 'Salon kosmetyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 50,
		objectAreaMax: 80,
		objectPriceMin: 1500,
		objectPriceMax: 3000},
	{	id: 7,
		companyType: 'Salon kosmetyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 50,
		objectAreaMax: 80,
		objectPriceMin: 1500,
		objectPriceMax: 3000},
	{	id: 8,
		companyType: 'Salon kosmetyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 50,
		objectAreaMax: 80,
		objectPriceMin: 1500,
		objectPriceMax: 3000},
	{	id: 9,
		companyType: 'Salon kosmetyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 50,
		objectAreaMax: 80,
		objectPriceMin: 1500,
		objectPriceMax: 3000}
];