import {objectSearched} from './objectSearched'

export const lastSearched: objectSearched[] = [
	{	id: 1,
		name: 'Tytuł ogłoszenia',
		owner: 1,
		companyType: 'Kancelaria prawnicza',
		transactionType: 'Wynajem',
		objectType: 'biuro',
		objectLocation: 'Warszawa',
		objectAreaMin: 250,
		objectAreaMax: 350,
		objectPriceMin: 10000,
		objectPriceMax: 15000,
		created_at: '2019-07-14 20:50:20'},
	{	id: 2,
		name: 'Tytuł ogłoszenia',
		owner: 1,
		companyType: 'Salon kosmetyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 50,
		objectAreaMax: 80,
		objectPriceMin: 1500,
		objectPriceMax: 3000,
		created_at: '2019-07-14 20:50:20'},
	{	id: 3,
		name: 'Tytuł ogłoszenia',
		owner: 1,
		companyType: 'Programista',
		transactionType: 'Wynajem',
		objectType: 'biuro',
		objectLocation: 'Warszawa',
		objectAreaMin: 15,
		objectAreaMax: 20,
		objectPriceMin: 500,
		objectPriceMax: 800,
		created_at: '2019-07-14 20:50:20'},
	{	id: 4,
		name: 'Tytuł ogłoszenia',
		owner: 1,
		companyType: 'Sklep specjalistyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 150,
		objectAreaMax: 200,
		objectPriceMin: 5000,
		objectPriceMax: 8000,
		created_at: '2019-07-14 20:50:20'},
	{	id: 5,
		name: 'Tytuł ogłoszenia',
		owner: 1,
		companyType: 'Salon kosmetyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 50,
		objectAreaMax: 80,
		objectPriceMin: 1500,
		objectPriceMax: 3000,
		created_at: '2019-07-14 20:50:20'},
	{	id: 6,
		name: 'Tytuł ogłoszenia',
		owner: 1,
		companyType: 'Salon kosmetyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 50,
		objectAreaMax: 80,
		objectPriceMin: 1500,
		objectPriceMax: 3000,
		created_at: '2019-07-14 20:50:20'},
	{	id: 7,
		name: 'Tytuł ogłoszenia',
		owner: 1,
		companyType: 'Salon kosmetyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 50,
		objectAreaMax: 80,
		objectPriceMin: 1500,
		objectPriceMax: 3000,
		created_at: '2019-07-14 20:50:20'},
	{	id: 8,
		name: 'Tytuł ogłoszenia',
		owner: 1,
		companyType: 'Salon kosmetyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 50,
		objectAreaMax: 80,
		objectPriceMin: 1500,
		objectPriceMax: 3000,
		created_at: '2019-07-14 20:50:20'},
	{	id: 9,
		name: 'Tytuł ogłoszenia',
		owner: 1,
		companyType: 'Salon kosmetyczny',
		transactionType: 'Wynajem',
		objectType: 'lokal usługowy',
		objectLocation: 'Warszawa',
		objectAreaMin: 50,
		objectAreaMax: 80,
		objectPriceMin: 1500,
		objectPriceMax: 3000,
		created_at: '2019-07-14 20:50:20'}
];